import { icon } from './icons.js';
import { config, safeUrl } from '../config.js';

export const wordmark = (small = false) => `<span class="wordmark ${small ? 'small' : ''}">GENELYRA<sup>™</sup></span><span class="brand-tagline">Where Ideas Become Engines.</span>`;
export function Header() {
  const store = safeUrl(config.storeUrl);
  return `<header class="site-header"><a class="brand" href="#home" aria-label="GENELYRA home">${wordmark()}</a>
    <nav class="desktop-nav" aria-label="Main navigation"><a href="#home" class="active">Home</a><a href="#generators">Generators</a><button data-dialog="bundles">Bundles</button><a href="#categories">Collections</a><a href="#how-it-works">How It Works</a><a href="#about">About</a><button data-dialog="faq">FAQ</button><a href="#newsletter">Contact</a></nav>
    <form class="search" role="search"><label class="sr-only" for="search">Search generators</label><input id="search" type="search" placeholder="Search generators…" autocomplete="off"/><button aria-label="Search generators">${icon('search')}</button></form>
    ${store ? `<a class="button gold shop" href="${store}" target="_blank" rel="noopener noreferrer">Shop Now ${icon('arrow')}</a>` : `<button class="button gold shop" data-dialog="store">Shop coming soon ${icon('arrow')}</button>`}
    <button class="menu-toggle icon-button" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav">${icon('menu')}</button>
    <nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden><a href="#home">Home</a><a href="#generators">Generators</a><a href="#categories">Collections</a><a href="#how-it-works">How It Works</a><a href="#about">Our Story</a><button data-dialog="faq">FAQ</button><a href="#newsletter">Contact</a>${store ? `<a href="${store}" target="_blank" rel="noopener noreferrer">Shop Now ${icon('arrow')}</a>` : ''}</nav>
    <div class="reading-progress" aria-hidden="true"></div></header>`;
}
export function Hero() {
  return `<section id="home" class="hero" aria-labelledby="hero-title"><picture class="hero-art"><source srcset="/assets/hero-960.webp 960w, /assets/hero-1920.webp 1920w" sizes="100vw" type="image/webp"/><img src="/assets/hero-1920.webp" width="1920" height="640" alt="A creator in a black leather jacket and sunglasses in a gold and violet illuminated studio" fetchpriority="high"/></picture>
    <div class="hero-shade"></div><div class="hero-copy"><p class="eyebrow entrance">Create <b>✦</b> Design <b>✦</b> Build <b>✦</b> Different</p><h1 id="hero-title" class="entrance metallic">GENELYRA<sup>™</sup></h1><p class="hero-tagline entrance">Where Ideas Become Engines.</p><p class="hero-description entrance">For creators, dreamers, small businesses, and visionaries. From fanwear to fashion, art, business, kids, and beyond — welcome to a universe of creative possibilities.</p>
    <div class="hero-actions entrance"><a class="button gold" href="#generators">Explore Generators ${icon('arrow')}</a><button class="button outline" data-dialog="experience"><span class="play-circle">${icon('play')}</span> Watch The Experience</button></div>
    <div class="hero-values entrance">${[['diamond','Creative<br>Power'],['crown','Professional<br>Quality'],['people','Built for<br>Creators'],['infinity','A universe<br>of possibilities']].map(([i,t])=>`<div>${icon(i)}<span>${t}</span></div>`).join('')}</div></div>
    <div class="studio-mantra" aria-hidden="true">Ideas<br>Design<br>Create<br>Execute<br>Repeat.</div><p class="hero-script" aria-hidden="true">Make<br>Create<br>Design<br>Build<br>Different.</p><a class="scroll-cue" href="#generators" aria-label="Scroll to generators"><span>Scroll</span>${icon('arrow')}</a>
    </section>`;
}
export function HowItWorks() {
  const steps = [['search','Browse','Explore the growing GENELYRA collection.'],['cart','Purchase','Explore available products in our Beacons store.'],['user','Access','Follow the access instructions with your purchase.'],['spark','Create','Bring your next creative idea to life.']];
  return `<section id="how-it-works" class="how-section reveal" aria-labelledby="how-title"><div class="how-content"><h2 id="how-title" class="section-title">How GENELYRA Works <span></span></h2><ol class="steps">${steps.map(([i,title,body],n)=>`<li><div class="step-top"><span class="step-number">0${n+1}</span>${icon(i)}</div><div class="step-copy"><h3>${title}</h3><p>${body}</p></div></li>`).join('')}</ol></div><aside id="about" class="story"><div><blockquote>“Better Tools.<br>Bigger Ideas.<br>Brighter Tomorrows.”</blockquote><button class="button gold" data-dialog="story">Our Story ${icon('arrow')}</button></div><span class="story-neon" aria-hidden="true">Same creators.<br>A brighter<br>tomorrow.</span></aside></section>`;
}
export function Footer() {
  return `<footer id="newsletter" class="site-footer reveal"><section class="newsletter" aria-labelledby="newsletter-title"><h2 id="newsletter-title" class="section-title pink">Join the GENELYRA Movement</h2><p>Get exclusive drops, updates, and creative inspiration.</p><form id="newsletter-form" novalidate><label class="sr-only" for="email">Your email address</label><div class="email-field"><input id="email" name="email" type="email" autocomplete="email" placeholder="Your email address" required aria-describedby="newsletter-status"/><button class="button gold" type="submit">Subscribe ${icon('arrow')}</button></div><p id="newsletter-status" class="form-status" role="status" aria-live="polite">${config.newsletter.endpoint ? 'Subscribe for news from GENELYRA.' : 'Newsletter launching soon. Sign-up is not yet available.'}</p></form></section><div class="footer-values">${[['people','A creator<br>community'],['heart','Creative news<br>& early access'],['chart','Room to<br>grow with you'],['star','New ideas.<br>More possibilities.']].map(([i,t])=>`<div>${icon(i)}<span>${t}</span></div>`).join('')}</div><div class="footer-brand"><a class="brand" href="#home">${wordmark(true)}</a><p>© ${new Date().getFullYear()} Genelyra. All rights reserved.</p><button class="text-button" data-dialog="contact">${icon('mail')} Get in touch</button></div></footer>`;
}
