import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('verification', {recursive:true});
const browser = await chromium.launch({channel:'msedge',headless:true});
const page = await browser.newPage({viewport:{width:1536,height:1024},reducedMotion:'reduce'});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173/',{waitUntil:'load'});
await page.evaluate(()=>document.fonts.ready);
await page.locator('.site-footer').scrollIntoViewIfNeeded();
await page.evaluate(()=>scrollTo(0,0));
await page.screenshot({path:'verification/desktop.png',fullPage:true});
assert.equal(await page.locator('h1').textContent(),'GENELYRA™');
assert.equal(await page.locator('.generator-card').count(),6);
assert.ok(await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)));
await page.locator('[data-category="art"]').click();
assert.equal(await page.locator('.empty-state').count(),1);
await page.locator('[data-reset]').click();
await page.locator('#search').fill('fanwear');
assert.equal(await page.locator('.generator-card').count(),1);
await page.locator('[data-product="fanwear-forge"]').click();
assert.equal(await page.locator('dialog').isVisible(),true);
assert.equal(await page.locator('dialog .unavailable').isDisabled(),true);
await page.keyboard.press('Escape');
assert.equal(await page.locator('[data-product="fanwear-forge"]').evaluate(el=>el===document.activeElement),true);
await page.locator('#search').fill('');
await page.setViewportSize({width:1100,height:900});
const track=page.locator('#generator-track');
await track.focus();await page.keyboard.press('End');
assert.ok(await track.evaluate(el=>el.scrollLeft>0));
await page.keyboard.press('Home');
assert.ok(await track.evaluate(el=>el.scrollLeft<=1));
await page.locator('.next').click();
assert.ok(await track.evaluate(el=>el.scrollLeft>0));
await track.focus();await page.keyboard.press('Home');
const trackBox=await track.boundingBox();
await page.mouse.move(trackBox.x+trackBox.width-30,trackBox.y+80);
await page.mouse.down();
await page.mouse.move(trackBox.x+100,trackBox.y+80,{steps:12});
await page.mouse.up();
assert.ok(await track.evaluate(el=>el.scrollLeft>0),'Mouse drag scrolls carousel');
await page.locator('#email').fill('invalid');
await page.locator('#newsletter-form button').click();
assert.match(await page.locator('#newsletter-status').textContent(),/valid email/);
await page.locator('#email').fill('test@example.com');
await page.locator('#newsletter-form button').click();
assert.match(await page.locator('#newsletter-status').textContent(),/has not been submitted/);
for(const width of [320,390,768,1024,1536]){
 await page.setViewportSize({width,height:900});
 await page.evaluate(()=>scrollTo(0,0));
 const overflow=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1&&!e.closest('.generator-track')).map(e=>[e.tagName,e.className,Math.round(e.getBoundingClientRect().right)]));
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Horizontal overflow at ${width}px: ${JSON.stringify(overflow)}`);
 if(width===390){
  await page.locator('.menu-toggle').click();
  assert.equal(await page.locator('#mobile-nav').isVisible(),true);
  await page.locator('#mobile-nav a[href="#generators"]').click();
  assert.equal(await page.locator('#mobile-nav').isVisible(),false);
  await page.reload({waitUntil:'load'});
  await page.locator('.site-footer').scrollIntoViewIfNeeded();
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'verification/mobile.png',fullPage:true});
 }
}
assert.deepEqual(errors,[]);
await page.emulateMedia({reducedMotion:'no-preference'});
await page.reload({waitUntil:'load'});
await page.locator('.hero').hover();
await page.locator('#generators').scrollIntoViewIfNeeded();
await page.locator('.generator-card').first().hover();
assert.equal(await page.locator('.hero-copy h1').evaluate(e=>getComputedStyle(e).animationName.includes('metallic')),true);
await page.emulateMedia({reducedMotion:'reduce'});
assert.equal(await page.locator('.hero-copy h1').evaluate(e=>getComputedStyle(e).animationName),'none');
await browser.close();
console.log('UI verification passed: images, filters, search, dialogs/focus, carousel keyboard/arrows, newsletter validation/unavailable, mobile menu, five responsive widths, no JS errors.');
